### ISSUE TITLE
kobo touch touchscreen freeze

### ISSUE THREAD

**Issue by thejoedoe** [kobolabs/Kobo-Reader#83]
it's a (used condition) kobo touch N905B (not the newest model) with neonode v1. "uname -a" gives "Linux (none) 2.6.35.3-850-gbc67621+ #328 PREEMPT Thu Dec 22 14:41:49 CST 2016 armv7l GNU/Linux"

/sys/power/wakeup_count increases rapidly (false alarms). after some hours the touchscreen stops sending events and the wakeup_count stops increasing. must full restart. wakeup count has made it to different numbers above 300,000 or as low as 17,000. there is no kernel source in this repo. with version 2.6.35.3 and the code that defines wakeup_count.

using "unbind" in /sys/bus gives same effect of freeze and stopping wakeup_count. also removes /sys/class/input/(event1,input1) and /dev/event1. "bind" does not work (lwn.net says it's like unbind).

if the touchscreen driver were compiled as a module (only small changes needed) maybe it could be modified for wakeup_count, or is it the hardware device sending signals directly to the kernel if bound? but last time I tried to build an identical kernel it built but didn't work. I also want to update to kernel 4.

**Comment by geek1011** [comment]
> there is no kernel source in this repo. with version 2.6.35.3 and the code that defines wakeup_count.

Are you sure it is not https://github.com/kobolabs/Kobo-Reader/blob/master/hw/imx507/linux-2.6.35.3.tar.bz2 or https://github.com/kobolabs/Kobo-Reader/blob/master/hw/imx508/ntx/linux-2.6.35.3.tar.gz?

> using "unbind" in /sys/bus

What exactly are you unbinding in /sys/bus? Also, you need to pass what you want to re-bind to `bind`.

> I also want to update to kernel 4.

What would be the purpose of this? It would probably be a lot of work for little to no benefit.

> if the touchscreen driver were compiled as a module (only small changes needed) maybe it could be modified for wakeup_count

I don't think this is the root cause of whatever issue you are having. It's probably a side-effect of something else.

> but last time I tried to build an identical kernel it built but didn't work

What didn't work about it?

Also, it would probably be helpful to attach the output of `dmesg`.

**Comment by thejoedoe** [comment]
I forgot to update the firmware.

**Comment by thejoedoe** [comment]
This issue was closed.
